### ISSUE TITLE
give bot users in the post feed a tag to show theyre a bot

### ISSUE THREAD

**Issue by Ategon** [PangoraWeb/pangora-ui#17]
Similar to the way lemmy-ui has one (but showing Bot instead of B) and in a similar format to the bot tag in the community moderator list currently in Pangora-UI
![image](https://github.com/PangoraWeb/pangora-ui/assets/73616169/ed881595-cc3f-4c41-aa88-b96a419105d5)

**Comment by sha-ahammed** [comment]
Hi @Ategon, I would like to work on this.
